default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
### dev
#  password: "nodriza.01"
#  socket: /var/lib/mysql/mysql.sock
####mac
  password: "root"
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: pamma_dev

test:
  <<: *default
  database: pamma_test

#production:
  #<<: *default
  #database: pamma_dev
  #username: root
  #password: <%= ENV['ARCANEGRA_DATABASE_PASSWORD'] %>
